services:
  database:
    image: postgres
    restart: always
    volumes:
    - database_volume:/var/lib/postgresql/data
    ports:
    - 5432
    env_file: .env.database

  backend:
    build: ./manga-backend
    ports:
      - "8000:8000"
    env_file: .env.backend
    depends_on: [database]

volumes:
  database_volume:
