services:
  database:
    image: postgres
    restart: always
    volumes:
    - database_volume:/var/lib/postgresql/data
    ports:
    - 5432
    env_file: backend/env/.env.database

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: backend/env/.env.backend
    depends_on: [database]
    volumes:
      - ./static:/app/static

  frontend:
    build: ./frontend
    ports:
      - "81:80"

  nginx:
    build: ./nginx
    ports:
      - "80:80"

volumes:
  database_volume:
