services:
  database:
    image: postgres
    restart: always
    volumes:
    - database_volume:/var/lib/postgresql/data
    ports:
    - 5432
    environment:
      - POSTGRES_PASSWORD=password

  backend:
    image: backend
    build: ./manga-backend
    command: "alembic upgrade head"
    ports:
      - "8000:8000"
    env_file: .env.backend
    depends_on: [database, alembic-upgrade]

volumes:
  database_volume:
